### 1. Load the data

In [1]:
from pathlib import Path

import pandas as pd


PROCESSED_DATA_DIR = Path("../data/processed")

community_assignments = pd.read_csv(
    PROCESSED_DATA_DIR / "community_assignments.csv"
)

clean_edges = pd.read_csv(
    PROCESSED_DATA_DIR / "clean_story_keyword_edges.csv"
)

print("Community assignments:", community_assignments.shape)
print("Clean keyword edges:", clean_edges.shape)

display(community_assignments.head())
display(clean_edges.head())

Community assignments: (1266, 3)
Clean keyword edges: (20720, 3)

   story_id  louvain_community  greedy_community
0      8193                 18                 0
1         2                  0                17
2     16387                 18                 0
3     16410                  1                 2
4      8226                 12                 0

   story_id  keyword_id     keyword
0      1319         929     Buttern
1      1453          30   on cattle
2     15342         206  Etymologie
3      5811        5813  Herrenhaus
4      3616          29     witches

### 2. story ID validation

In [2]:
community_assignments["story_id"] = (
    community_assignments["story_id"].astype(str)
)

clean_edges["story_id"] = (
    clean_edges["story_id"].astype(str)
)

### 3. Join stories with their Louvain communities

In [3]:
community_keywords = clean_edges.merge(
    community_assignments[
        ["story_id", "louvain_community"]
    ],
    on="story_id",
    how="inner"
)

print("Joined rows:", len(community_keywords))
display(community_keywords.head())

Joined rows: 5783

  story_id  keyword_id             keyword  louvain_community
0    15342         206          Etymologie                  9
1     9307           4  historical legends                  9
2    10498         354                Berg                 10
3    17765          41       local legends                 18
4      822         824  weiblich: Deichsel                 16

### 4. Count keywords inside each community

In [4]:
keyword_counts = (
    community_keywords
    .groupby(
        ["louvain_community", "keyword"]
    )["story_id"]
    .nunique()
    .reset_index(name="story_count")
)

keyword_counts = keyword_counts.sort_values(
    ["louvain_community", "story_count"],
    ascending=[True, False]
)

display(keyword_counts.head(20))

    louvain_community                          keyword  story_count
0                   0                    Danish people           12
1                   0                             Däne           12
2                   0                Sage, historische           12
3                   0               historical legends           12
10                  1                         Franzose           96
14                  1                Sage, historische           96
18                  1               historical legends           96
11                  1                    French people           95
17                  1           from the french period            2
4                   1       30-/100-year war, blending            1
5                   1                           Brücke            1
6                   1                   Carwitz-Brücke            1
7                   1                   Carwitz-bridge            1
8                   1                    Danish people            1
9                   1                             Däne            1
12                  1  French people etc., search town            1
13                  1                        Lokalsage            1
15                  1                            Stadt            1
16                  1                      destruction            1
19                  1             local legends: varia            1

### 5. Select the top 10 keywords per community

In [5]:
TOP_KEYWORDS = 10

top_keywords = (
    keyword_counts
    .groupby("louvain_community")
    .head(TOP_KEYWORDS)
    .reset_index(drop=True)
)

display(top_keywords)

     louvain_community             keyword  story_count
0                    0       Danish people           12
1                    0                Däne           12
2                    0   Sage, historische           12
3                    0  historical legends           12
4                    1            Franzose           96
..                 ...                 ...          ...
154                 18       Fachliteratur           26
155                 18         destruction           26
156                 18       goldene Wiege           26
157                 18     Untergang: Lit.           25
158                 18      Untergangssage           25

[159 rows x 3 columns]

### 6. Print the results clearly

In [6]:
for community_id, group in top_keywords.groupby(
    "louvain_community"
):
    print(f"\nCommunity {community_id}")

    for _, row in group.iterrows():
        print(
            f"- {row['keyword']}: "
            f"{row['story_count']} stories"
        )

Community 0
- Danish people: 12 stories
- Däne: 12 stories
- Sage, historische: 12 stories
- historical legends: 12 stories

Community 1
- Franzose: 96 stories
- Sage, historische: 96 stories
- historical legends: 96 stories
- French people: 95 stories
- from the french period: 2 stories
- 30-/100-year war, blending: 1 stories
- Brücke: 1 stories
- Carwitz-Brücke: 1 stories
- Carwitz-bridge: 1 stories
- Danish people: 1 stories

Community 2
- Räuber: 31 stories
- Störtebecker: 31 stories
- robbers: 31 stories
- Störtebecker - Gödeke Michel: 30 stories
- Räubersage: 1 stories

Community 3
- Lokalsage: 62 stories
- Raubritter: 62 stories
- local legends: varia: 62 stories
- Robber-knight: 41 stories
- Robber-knight gen.: 21 stories
- Berg: 1 stories
- Etymologie: 1 stories
- Mountain open: 1 stories
- local legends: churches and passages: 1 stories

Community 4
- Sage, historische: 20 stories
- from the french period: 20 stories
- historical legends: 20 stories

Community 5
- Wasser: 56 stories
- water: 56 stories
- See (der): 33 stories
- Opfer: 29 stories
- ausmessen: 23 stories
- ablassen: 19 stories
- Victim: 16 stories
- ablassen, See ausmessen etc.: 16 stories
- Victim, last hour has come: 10 stories
- grundlos, ausmessen etc.: 4 stories

Community 6
- Sage, historische: 59 stories
- historical legends: 59 stories
- 30-/100-year war, blending: 46 stories
- Schweden: 14 stories
- Sweden: 14 stories
- Historic, elderly: 1 stories

Community 7
- Räuber: 119 stories
- Viting: 119 stories
- robbers: 119 stories
- Lit.: 4 stories
- Sohn: 4 stories
- Viting /raubt Mädchen - 7 Söhne - verraten: 4 stories
- Volkssage: 4 stories
- lit.: 4 stories
- rauben: 4 stories
- weiblich: 4 stories

Community 8
- Berg: 66 stories
- Lokalsage: 66 stories
- local legends: varia: 66 stories
- Mountain open: 23 stories
- Berg nicht fortschaffen: 13 stories
- Mountain: singing, thunder etc.: 13 stories
- Berge hohl: 8 stories
- Berg: heilige Berge; Zwerge: 3 stories
- Mountains: 3 stories
- Berg vom Riesen zusammengetragen: 2 stories

Community 9
- Lokalsage: 54 stories
- Etymologie: 44 stories
- local legends: churches and passages: 44 stories
- Historic, elderly: 26 stories
- Sage, historische: 26 stories
- historical legends: 26 stories
- local legends: varia: 10 stories
- Name: 7 stories
- Ritter: 5 stories
- Namenswechsel: 4 stories

Community 10
- Berg: 47 stories
- Riese: 47 stories
- giants: 47 stories
- tragen Berge zusammen: 47 stories
- zusammentragen: 47 stories
- Kenntnis von den Wenden, meckl.: 1 stories
- Mecklenburg: 1 stories
- Sage, historische: 1 stories
- Wenden (Nation): 1 stories
- historical legends: 1 stories

Community 11
- Russe: 18 stories
- Russian people: 18 stories
- Sage, historische: 18 stories
- historical legends: 18 stories
- Toter: 15 stories
- dead: 15 stories
- kämpfen: 15 stories
- to fight: 15 stories

Community 12
- Fachliteratur: 43 stories
- Lit.: 43 stories
- Literature: 43 stories
- bells: 36 stories
- Wasser: 28 stories
- water: 28 stories
- Volkssage: 23 stories
- Literatur: 16 stories
- Tod: 16 stories
- Totensage: 16 stories

Community 13
- Franzose: 23 stories
- French people etc., search town: 23 stories
- Stadt: 23 stories
- destruction: 23 stories

Community 14
- Mecklenburg: 47 stories
- Sage, historische: 47 stories
- historical legends: 47 stories
- Berg: 25 stories
- Kaiser: 25 stories
- Kenntnis von den Wenden, meckl.: 25 stories
- Kyffhäuser: Kaiser im Berg: 25 stories
- Toter: 25 stories
- Wenden (Nation): 25 stories
- dead: 25 stories

Community 15
- Allg.: 48 stories
- Gen.: 48 stories
- Sage, historische: 48 stories
- historical legends: 48 stories
- 30-/100-year war, blending: 1 stories
- Etymologie: 1 stories
- Lokalsage: 1 stories
- Schweden: 1 stories
- Sweden: 1 stories
- local legends: churches and passages: 1 stories

Community 16
- Volkssage: 35 stories
- Wilde Jagd: 35 stories
- wild hunt: 35 stories
- Name: 23 stories
- Name: varia: 17 stories
- Hund: 7 stories
- Lokalsage: 7 stories
- local legends: 7 stories
- Bier: 6 stories
- Brot: 6 stories

Community 17
- Horse shoe etc.: 67 stories
- Hufeisen: 67 stories
- Lokalsage: 67 stories
- local legends: varia: 67 stories
- Kenntnis von den Wenden, meckl.: 2 stories
- Mecklenburg: 2 stories
- Sage, historische: 2 stories
- Wenden (Nation): 2 stories
- historical legends: 2 stories
- Name: 1 stories

Community 18
- Lokalsage: 101 stories
- local legends: 100 stories
- Schatzsage: 84 stories
- treasure: 83 stories
- haunting animals: 35 stories
- Fachliteratur: 26 stories
- destruction: 26 stories
- goldene Wiege: 26 stories
- Untergang: Lit.: 25 stories
- Untergangssage: 25 stories

### 7. Add community sizes and percentages

In [7]:
community_sizes = (
    community_assignments
    .groupby("louvain_community")["story_id"]
    .nunique()
    .rename("community_size")
)

top_keywords = top_keywords.merge(
    community_sizes,
    on="louvain_community",
    how="left"
)

top_keywords["percentage"] = (
    top_keywords["story_count"]
    / top_keywords["community_size"]
    * 100
).round(2)

display(top_keywords)

,louvain_community,keyword,story_count,community_size,percentage
0,0,Danish people,12,12,100.00
1,0,Däne,12,12,100.00
2,0,"Sage, historische",12,12,100.00
3,0,historical legends,12,12,100.00
4,1,Franzose,96,96,100.00
...,...,...,...,...,...
154,18,Fachliteratur,26,252,10.32
155,18,destruction,26,252,10.32
156,18,goldene Wiege,26,252,10.32
157,18,Untergang: Lit.,25,252,9.92
158,18,Untergangssage,25,252,9.92

In [8]:
for community_id, group in top_keywords.groupby(
    "louvain_community"
):
    community_size = group["community_size"].iloc[0]

    print(
        f"\nCommunity {community_id} "
        f"({community_size} stories)"
    )

    for _, row in group.iterrows():
        print(
            f"- {row['keyword']}: "
            f"{row['story_count']} stories "
            f"({row['percentage']}%)"
        )

Community 0 (12 stories)
- Danish people: 12 stories (100.0%)
- Däne: 12 stories (100.0%)
- Sage, historische: 12 stories (100.0%)
- historical legends: 12 stories (100.0%)

Community 1 (96 stories)
- Franzose: 96 stories (100.0%)
- Sage, historische: 96 stories (100.0%)
- historical legends: 96 stories (100.0%)
- French people: 95 stories (98.96%)
- from the french period: 2 stories (2.08%)
- 30-/100-year war, blending: 1 stories (1.04%)
- Brücke: 1 stories (1.04%)
- Carwitz-Brücke: 1 stories (1.04%)
- Carwitz-bridge: 1 stories (1.04%)
- Danish people: 1 stories (1.04%)

Community 2 (31 stories)
- Räuber: 31 stories (100.0%)
- Störtebecker: 31 stories (100.0%)
- robbers: 31 stories (100.0%)
- Störtebecker - Gödeke Michel: 30 stories (96.77%)
- Räubersage: 1 stories (3.23%)

Community 3 (62 stories)
- Lokalsage: 62 stories (100.0%)
- Raubritter: 62 stories (100.0%)
- local legends: varia: 62 stories (100.0%)
- Robber-knight: 41 stories (66.13%)
- Robber-knight gen.: 21 stories (33.87%)
- Berg: 1 stories (1.61%)
- Etymologie: 1 stories (1.61%)
- Mountain open: 1 stories (1.61%)
- local legends: churches and passages: 1 stories (1.61%)

Community 4 (20 stories)
- Sage, historische: 20 stories (100.0%)
- from the french period: 20 stories (100.0%)
- historical legends: 20 stories (100.0%)

Community 5 (56 stories)
- Wasser: 56 stories (100.0%)
- water: 56 stories (100.0%)
- See (der): 33 stories (58.93%)
- Opfer: 29 stories (51.79%)
- ausmessen: 23 stories (41.07%)
- ablassen: 19 stories (33.93%)
- Victim: 16 stories (28.57%)
- ablassen, See ausmessen etc.: 16 stories (28.57%)
- Victim, last hour has come: 10 stories (17.86%)
- grundlos, ausmessen etc.: 4 stories (7.14%)

Community 6 (59 stories)
- Sage, historische: 59 stories (100.0%)
- historical legends: 59 stories (100.0%)
- 30-/100-year war, blending: 46 stories (77.97%)
- Schweden: 14 stories (23.73%)
- Sweden: 14 stories (23.73%)
- Historic, elderly: 1 stories (1.69%)

Community 7 (122 stories)
- Räuber: 119 stories (97.54%)
- Viting: 119 stories (97.54%)
- robbers: 119 stories (97.54%)
- Lit.: 4 stories (3.28%)
- Sohn: 4 stories (3.28%)
- Viting /raubt Mädchen - 7 Söhne - verraten: 4 stories (3.28%)
- Volkssage: 4 stories (3.28%)
- lit.: 4 stories (3.28%)
- rauben: 4 stories (3.28%)
- weiblich: 4 stories (3.28%)

Community 8 (66 stories)
- Berg: 66 stories (100.0%)
- Lokalsage: 66 stories (100.0%)
- local legends: varia: 66 stories (100.0%)
- Mountain open: 23 stories (34.85%)
- Berg nicht fortschaffen: 13 stories (19.7%)
- Mountain: singing, thunder etc.: 13 stories (19.7%)
- Berge hohl: 8 stories (12.12%)
- Berg: heilige Berge; Zwerge: 3 stories (4.55%)
- Mountains: 3 stories (4.55%)
- Berg vom Riesen zusammengetragen: 2 stories (3.03%)

Community 9 (78 stories)
- Lokalsage: 54 stories (69.23%)
- Etymologie: 44 stories (56.41%)
- local legends: churches and passages: 44 stories (56.41%)
- Historic, elderly: 26 stories (33.33%)
- Sage, historische: 26 stories (33.33%)
- historical legends: 26 stories (33.33%)
- local legends: varia: 10 stories (12.82%)
- Name: 7 stories (8.97%)
- Ritter: 5 stories (6.41%)
- Namenswechsel: 4 stories (5.13%)

Community 10 (47 stories)
- Berg: 47 stories (100.0%)
- Riese: 47 stories (100.0%)
- giants: 47 stories (100.0%)
- tragen Berge zusammen: 47 stories (100.0%)
- zusammentragen: 47 stories (100.0%)
- Kenntnis von den Wenden, meckl.: 1 stories (2.13%)
- Mecklenburg: 1 stories (2.13%)
- Sage, historische: 1 stories (2.13%)
- Wenden (Nation): 1 stories (2.13%)
- historical legends: 1 stories (2.13%)

Community 11 (32 stories)
- Russe: 18 stories (56.25%)
- Russian people: 18 stories (56.25%)
- Sage, historische: 18 stories (56.25%)
- historical legends: 18 stories (56.25%)
- Toter: 15 stories (46.88%)
- dead: 15 stories (46.88%)
- kämpfen: 15 stories (46.88%)
- to fight: 15 stories (46.88%)

Community 12 (82 stories)
- Fachliteratur: 43 stories (52.44%)
- Lit.: 43 stories (52.44%)
- Literature: 43 stories (52.44%)
- bells: 36 stories (43.9%)
- Wasser: 28 stories (34.15%)
- water: 28 stories (34.15%)
- Volkssage: 23 stories (28.05%)
- Literatur: 16 stories (19.51%)
- Tod: 16 stories (19.51%)
- Totensage: 16 stories (19.51%)

Community 13 (23 stories)
- Franzose: 23 stories (100.0%)
- French people etc., search town: 23 stories (100.0%)
- Stadt: 23 stories (100.0%)
- destruction: 23 stories (100.0%)

Community 14 (70 stories)
- Mecklenburg: 47 stories (67.14%)
- Sage, historische: 47 stories (67.14%)
- historical legends: 47 stories (67.14%)
- Berg: 25 stories (35.71%)
- Kaiser: 25 stories (35.71%)
- Kenntnis von den Wenden, meckl.: 25 stories (35.71%)
- Kyffhäuser: Kaiser im Berg: 25 stories (35.71%)
- Toter: 25 stories (35.71%)
- Wenden (Nation): 25 stories (35.71%)
- dead: 25 stories (35.71%)

Community 15 (48 stories)
- Allg.: 48 stories (100.0%)
- Gen.: 48 stories (100.0%)
- Sage, historische: 48 stories (100.0%)
- historical legends: 48 stories (100.0%)
- 30-/100-year war, blending: 1 stories (2.08%)
- Etymologie: 1 stories (2.08%)
- Lokalsage: 1 stories (2.08%)
- Schweden: 1 stories (2.08%)
- Sweden: 1 stories (2.08%)
- local legends: churches and passages: 1 stories (2.08%)

Community 16 (43 stories)
- Volkssage: 35 stories (81.4%)
- Wilde Jagd: 35 stories (81.4%)
- wild hunt: 35 stories (81.4%)
- Name: 23 stories (53.49%)
- Name: varia: 17 stories (39.53%)
- Hund: 7 stories (16.28%)
- Lokalsage: 7 stories (16.28%)
- local legends: 7 stories (16.28%)
- Bier: 6 stories (13.95%)
- Brot: 6 stories (13.95%)

Community 17 (67 stories)
- Horse shoe etc.: 67 stories (100.0%)
- Hufeisen: 67 stories (100.0%)
- Lokalsage: 67 stories (100.0%)
- local legends: varia: 67 stories (100.0%)
- Kenntnis von den Wenden, meckl.: 2 stories (2.99%)
- Mecklenburg: 2 stories (2.99%)
- Sage, historische: 2 stories (2.99%)
- Wenden (Nation): 2 stories (2.99%)
- historical legends: 2 stories (2.99%)
- Name: 1 stories (1.49%)

Community 18 (252 stories)
- Lokalsage: 101 stories (40.08%)
- local legends: 100 stories (39.68%)
- Schatzsage: 84 stories (33.33%)
- treasure: 83 stories (32.94%)
- haunting animals: 35 stories (13.89%)
- Fachliteratur: 26 stories (10.32%)
- destruction: 26 stories (10.32%)
- goldene Wiege: 26 stories (10.32%)
- Untergang: Lit.: 25 stories (9.92%)
- Untergangssage: 25 stories (9.92%)

### 8. Save the keyword summary

In [9]:
OUTPUT_PATH = (
    PROCESSED_DATA_DIR
    / "community_top_keywords.csv"
)

top_keywords.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Saved to:")
print(OUTPUT_PATH)

Saved to:
..\data\processed\community_top_keywords.csv

## Keyword interpretation conclusion

The cleaned story-keyword relationships were joined with the Louvain community
assignments.

For every community, the ten keywords occurring in the largest number of
stories were identified. The percentage of stories containing each keyword was
also calculated.

These keyword profiles provide an initial interpretation of the themes
represented by each detected community.